export default {
  "vagueVerb": [
    "re-enacting",
    "enacting",
    "classifying",
    "(re-)classifying",
    "black-boxing",
    "assembling",
    "(re-)assembling",
    "differentiating",
    "configuring",
    "(re-)configuring",
    "(re-)drawing",
    "extending",
    "changing",
    "(inter-)changing",
    "tracing the trail of",
    "negotiating",
    "(re-) negotiating",
    "emerging",
    "materializing",
    "scaffolding",
    "establishing",
    "intersecting",
    "unmaking"
  ],
  "vagueNoun": [
    "inaccessibility",
    "interface",
    "contour",
    "sphere",
    "togetherness",
    "exploration",
    "politic",
    "experiment",
    "experience",
    "domination",
    "power structure",
    "network",
    "art",
    "object",
    "work",
    "topology",
    "imaginary",
    "embodiment",
    "risk",
    "invisibility",
    "materiality",
    "immateriality",
    "development",
    "mess",
    "commodification",
    "collaboration"
  ],
  "method": [
    "ethnographic",
    "performative",
    "interdisciplinary",
    "feminist",
    "reflexive"
  ],
  "nounCountable": [
    "laboratory",
    "vehicle",
    "subject",
    "building",
    "home",
    "satellite",
    "image",
    "bridge",
    "publication",
    "ship"
  ],
  "nounUncountable": [
    "soil",
    "water",
    "waste",
    "code",
    "data",
    "art",
    "power",
    "work"
  ],
  "adjective": [
    "public",
    "interdisciplinary",
    "capitalist",
    "postmodern",
    "dystopian",
    "utopian",
    "multiple",
    "entangled",
    "scientific",
    "algorithmic",
    "medical",
    "biosocial",
    "emergent",
    "community-based",
    "everyday",
    "unexplained",
    "techno-scientific"
  ],
  "century": "#nounUncountable# in the 21st century",
  "doingPart": "#vagueVerb# the #vagueNoun# of the #adjective# #vagueNoun#",
  "thingAs":"#adjective# #vagueNoun.s# for #vagueVerb# #vagueNoun.s#",
  "methodUse":"#vagueVerb# #vagueNoun.s# from a #method# perspective",
  "xAsY": "#nounUncountable# as #vagueNoun#",
  "just": "“It is just #nounUncountable#!”",
  "xAndY": "#nounUncountable# and #vagueNoun.s#",
  "question": "What is #nounUncountable#",
  "list": "#vagueVerb# #vagueNoun#, #vagueNoun# and #vagueNoun#",
  "whatIs":"What is a #nounCountable#",
  "preColon": [
    "#xAndY#:",
    "#xAsY#:",
    "#century#:",
    "#just#:",
    "#question#?",
    "#whatIs#?"
  ],
  "postColon": [
    "#list#",
    "#doingPart#",
    "#thingAs#",
    "#methodUse#"
  ],
  "origin": "#preColon.capitalize# #postColon.capitalize#"
}

