export default {
  "vagueVerb": [
    "re-enacting",
    "enacting",
    "classifying",
    "(re-)classifying",
    "black-boxing",
    "assembling",
    "(re-)assembling",
    "differentiating",
    "configuring",
    "(re-)configuring",
    "(re-)drawing",
    "extending",
    "changing",
    "(inter-)changing",
    "tracing the trail of",
    "negotiating",
    "(re-) negotiating",
    "emerging",
    "materializing",
    "scaffolding",
    "establishing",
    "intersecting",
    "unmaking",
    "engineering",
    "(en)countering",
    "encountering",
    "articulating",
    "relating",
    "ordering",
    "commodifying",
    "futuring",
    "radicalizing",
    "facilitating",
    "interrogating"
  ],
  "vagueNoun": [
    "inaccessibility",
    "interface",
    "contour",
    "sphere",
    "matter",
    "togetherness",
    "exploration",
    "experiment",
    "experience",
    "domination",
    "power structure",
    "network",
    "art",
    "object",
    "work",
    "topology",
    "imaginary",
    "embodiment",
    "risk",
    "invisibility",
    "materiality",
    "immateriality",
    "development",
    "enterprise",
    "mess",
    "commodification",
    "collaboration",
    "actor",
    "significance",
    "matter",
    "encounter",
    "resonance",
    "ambiguity",
    "multiplicity",
    "fluidity",
    "circulation",
    "zeitgeist",
    "movement",
    "inclusion",
    "paradox",
    "critique"
  ],
  "method": [
    "ethnographic",
    "performative",
    "interdisciplinary",
    "feminist",
    "reflexive",
    "postcolonialist",
    "artistical",
    "anthropological",
    "practice-based"
  ],
  "nounCountable": [
    "laboratory",
    "vehicle",
    "subject",
    "building",
    "home",
    "book",
    "spreadsheet",
    "database",
    "cell",
    "satellite",
    "image",
    "bridge",
    "publication",
    "ship",
    "observation",
    "infrastructure",
    "cyborg"
  ],
  "nounUncountable": [
    "water",
    "waste",
    "code",
    "data",
    "art",
    "power",
    "work",
    "business",
    "democracy",
    "software",
    "technology",
    "education",
    "governance",
    "nature",
    "decay",
    "pollution",
    "politics"
  ],
  "adjective": [
    "public",
    "interdisciplinary",
    "capitalist",
    "involved",
    "postmodern",
    "dystopian",
    "utopian",
    "multiple",
    "entangled",
    "scientific",
    "algorithmic",
    "medical",
    "epistemical",
    "biosocial",
    "emergent",
    "community-based",
    "everyday",
    "unexplained",
    "techno-scientific",
    "techno-legal",
    "engaged",
    "situated",
    "hybrid"
  ],
  "publicationThing": [
    "perpective on",
    "study of",
    "case study of",
    "investigation of",
    "writing about"
  ],
  "century": "#nounUncountable# in the 21st century",
  "doingPart": "#vagueVerb# the #vagueNoun# of the #adjective# #vagueNoun#",
  "xOfSomething": "#vagueNoun# of the #adjective# #vagueNoun#",
  "thingAs": "#adjective# #vagueNoun.s# for #vagueVerb# #vagueNoun.s#",
  "methodUse": "#vagueVerb# #vagueNoun.s# from #method.a# perspective",
  "xAsY": "#nounUncountable# as #vagueNoun#",
  "just": "“It is just #nounUncountable#!”",
  "xAndY": "#nounUncountable# and #vagueNoun.s#",
  "question": "What is #nounUncountable#",
  "list": "#vagueVerb# #vagueNoun#, #vagueNoun# and #vagueNoun#",
  "whatIs": "What is #nounCountable.a#",
  "aStudyOn": "#publicationThing.a# #adjective# #nounUncountable#",
  "chaintemplate": [
    "#firstnoun.s# of #secondnoun# and the #secondnoun# of #firstnoun.s#"
  ],
  "chain": [
    "#[firstnoun:#vagueNoun#][secondnoun:#vagueNoun#]chaintemplate#"
  ],
  "preColon": [
    "#chain#:",
    "#xAndY#:",
    "#xAsY#:",
    "#century#:",
    "#just#:",
    "#question#?",
    "#whatIs#?",
    "#xOfSomething#:"
  ],
  "postColon": [
    "#list#",
    "#doingPart#",
    "#thingAs#",
    "#methodUse#",
    "#aStudyOn#"
  ],
  "origin": "#preColon.capitalize# #postColon.capitalize#"
}
